import { glossary } from '../control-center.js';
import { CandidateActions, MarketStudyControl, StartControl } from './controls.js';

const nav = [
  ['⌂','Dashboard','Overview of everything'],['◇','Market Studies','Evidence-backed validation'],['♙','AI Team','See what each agent does'],['♨','Opportunities','New website ideas'],['□','Projects','All websites (new & live)'],['↗','SEO Growth','Track and improve SEO'],['▥','Analytics','Traffic, revenue, keywords'],['➤','Deployments','Domains, server, status'],['＄','Finances','Costs and earnings'],['▣','Knowledge Base','What AI has learned'],['⚙','Settings','Control and limits']
] as const;
const agents = [
  ['1','Researcher','Finds niches, keywords and market opportunities.','blue'],['2','Strategist','Decides what to build and how to make money.','violet'],['3','Designer','Creates accessible designs in Figma.','pink'],['4','Reviewer','Checks intent, usability and readiness.','orange'],['5','Developer','Builds approved websites in GitHub.','cyan'],['6','QA & SEO','Tests the website and technical SEO.','teal'],['7','DevOps','Handles approved VPS deployments.','indigo'],['8','Growth SEO','Improves sites from real evidence.','green'],['9','Monetization','Tracks costs, revenue and opportunities.','gold']
] as const;
type Overview = { workflows: number; opportunities: number; projects: number; approvals: number };
type Health = { database: string; temporal: string; researchProvider: string; reason: string };
type Activity = { runs: Array<{ id:string; state:string; updatedAt:string }>; events: Array<{ id:string; eventType:string; aggregateId:string; payload:Record<string,string>; occurredAt:string }> };
type Opportunity = { id:string; title:string; lifecycle:string; rationale:string; approvalId?:string; scorecard:{total?:number}; phase2Readiness?:{ready?:boolean}; limitations:string[]; evidence:Array<{sourceUrl:string;capturedAt:string;confidence:number}> };
type Finding = {id:string;dimension:string;classification:'fact'|'observation'|'inference'|'unknown';claim:string;confidence:number;evidenceIds:string[]};
type ProviderRun={providerId:string;capability:string;availability:string;reason:string;requestCount:number;paidCostCents:number;evidenceNature:'direct'|'proxy';geography:string;resolvesDimensions:string[];documentationUrl:string;limitations:string[]};
type ToolReview={repository:string;name:string;categories:string[];license:string;maintenanceStatus:string;securityConcerns:string;runtime:string;integrationDifficulty:string;recommendation:'USE'|'ADAPT'|'WATCH'|'REJECT';rationale:string;reviewedAt:string};
type StudyOpportunity = {id:string;title:string;rationale:string;recommendation:string;confidence:number;unknowns:string[];problem:string;audience:string;searchDemandHypothesis:string;searchIntent:string;productTypeHypothesis:string;monetizationHypothesis:string;trafficPotential:string;buildComplexity:string;defensibility:string;risks:string[];topicClusters:string[];queryExamples:string[];contentGaps:string[];toolGaps:string[];productFormats:string[];informationArchitecture:string[];phase2Readiness:{ready:boolean;blockers:string[]};scorecard:{total:number;evidenceCoverage:number;dimensions:Array<{dimension:string;classification:string;points:number;weight:number}>};findings:Finding[];evidence:Array<{id:string;sourceUrl:string;capturedAt:string;confidence:number;providerId:string;capability:string;subject:string;evidenceNature:'direct'|'proxy';geography:string;stale:boolean;freshUntil?:string;measurement?:{kind:string;value:number|null;unit:string;absoluteSearchDemand:false};limitations:string[]}>};
type MarketStudy = {id:string;brief:string;status:string;sourcePolicy:string;paidBudgetCents:number;requestLimit:number;timeLimitSeconds:number;createdAt:string;workflowState:string;providers:ProviderRun[];opportunities:StudyOpportunity[]};
const apiBase = process.env.API_INTERNAL_URL ?? 'http://127.0.0.1:4000/api';
async function runtime() {
  try {
    const [overview,health,activity,opportunities,studies,tools] = await Promise.all([
      fetch(`${apiBase}/overview`,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error();return r.json() as Promise<Overview>}),
      fetch(`${apiBase}/health`,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error();return r.json() as Promise<Health>}),
      fetch(`${apiBase}/activity`,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error();return r.json() as Promise<Activity>}),
      fetch(`${apiBase}/opportunities`,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error();return r.json() as Promise<Opportunity[]>}),
      fetch(`${apiBase}/market-studies`,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error();return r.json() as Promise<MarketStudy[]>}),
      fetch(`${apiBase}/open-source-tools`,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error();return r.json() as Promise<ToolReview[]>})
    ]);
    return { overview,health,activity,opportunities,studies,tools,available:true as const };
  } catch { return { overview:{workflows:0,opportunities:0,projects:0,approvals:0},health:null,activity:{runs:[],events:[]},opportunities:[],studies:[],tools:[],available:false as const }; }
}

export default async function Dashboard(){const data=await runtime(); const active=data.activity.runs[0]; const kpis = [['◎',String(data.overview.projects),'Projects','Persisted projects'],['♜',String(data.overview.workflows),'Workflow Runs','Persisted workflow history'],['♧',String(data.overview.opportunities),'Opportunities Found','Evidence-backed only'],['✓',String(data.overview.approvals),'Pending Approvals','Owner decisions needed'],['$','$0','Total Revenue','No recorded revenue']] as const; return <div className="shell">
  <aside className="sidebar">
    <div className="logo"><i>◉</i><span><b>AI Web Company</b><small>Find • Build • Rank • Grow</small></span></div>
    <nav>{nav.map(([icon,label,sub],i)=><a className={i===0?'active':''} href="#" key={label}><i>{icon}</i><span><b>{label}</b><small>{sub}</small></span></a>)}</nav>
    <div className="help"><i>?</i><span><b>Need Help?</b><small>Click any item to see a simple explanation.</small></span></div>
  </aside>
  <main>
    <header className="topbar">
      <div className="prompt"><i>✦</i><span>Tell the AI what you want or just click Start<small>e.g. “Find and build a new website” or “Improve SEO for all sites”</small></span></div>
      <div className="modes"><button className="chosen"><b>♟ Manual</b><small>You approve every step</small></button><button><b>◉ Supervised</b><small>AI works, asks for approvals</small></button><button className="auto"><b>ϟ Auto Pilot</b><small>Unavailable until limits are set</small></button></div>
      <button className="circle" aria-label="Notifications">♟</button><button className="circle owner" aria-label="Owner">●</button>
    </header>

    <section className="hero card">
      <div className="start"><div className="title"><i>ϟ</i><span><h1>Start the AI Web Company</h1><p>Let the AI find opportunities, design, build, deploy and grow websites for you.</p></span></div>{data.available?<StartControl/>:<button disabled>Runtime unavailable<small>Start local services first</small></button>}</div>
      <div className="journey find"><i>⌕</i><b>Find Opportunities</b><p>AI searches permitted public sources for evidence-backed ideas.</p></div>
      <div className="journey build"><i>‹/›</i><b>Build &amp; Launch</b><p>AI designs and develops only after your approval.</p></div>
      <div className="journey grow"><i>↗</i><b>Rank &amp; Grow</b><p>AI improves projects using genuine performance data.</p></div>
      <div className="kpis">{kpis.map(([icon,value,label,sub])=><article key={label}><i>{icon}</i><span><strong>{value}</strong><b>{label}</b><small>{sub}</small></span></article>)}</div>
    </section>

    <section className="market card evidenceRegistry">
      <div className="head"><div><h2>Open-source SEO capability review</h2><p>Reviewed building blocks, not installed integrations. Every candidate still needs a pinned-version security review.</p></div><em>● {data.tools.length} reviewed</em></div>
      <div className="toolGrid">{data.tools.map(tool=><article key={tool.repository}><div><b>{tool.name}</b><span className={`toolDecision ${tool.recommendation.toLowerCase()}`}>{tool.recommendation}</span></div><small>{tool.categories.join(' · ')}</small><p>{tool.rationale}</p><dl><dt>License</dt><dd>{tool.license}</dd><dt>Runtime</dt><dd>{tool.runtime}</dd><dt>Integration</dt><dd>{tool.integrationDifficulty}</dd><dt>Maintenance</dt><dd>{tool.maintenanceStatus}</dd></dl><details><summary>Security concerns</summary><p>{tool.securityConcerns}</p></details><a href={tool.repository} target="_blank" rel="noreferrer">Repository ↗</a></article>)}</div>
    </section>

    <section className="market card" id="market-studies">
      <div className="head"><div><h2>Market Validation</h2><p>Compare evidence, uncertainty and product hypotheses before selecting what to build.</p></div><em>● {data.studies[0]?.status ?? 'No study yet'}</em></div>
      {data.available&&<MarketStudyControl/>}
      {data.studies[0]?<MarketStudyView study={data.studies[0]}/>:<div className="noStudy"><b>No Market Study has been created.</b><span>Create one above. The system will preserve unavailable metrics as UNKNOWN—not estimate them.</span></div>}
    </section>

    <section className="team card"><div className="head"><h2>AI Team <span>(Your Virtual Company)</span></h2><em>● {data.available?'Runtime connected':'Runtime unavailable'}</em><button>View Team Details ›</button></div><div className="flow">{agents.map(([num,name,desc,color],i)=><div className="agentWrap" key={name}><article className={`agent ${color}`}><div><i>{num}</i><b>{name}</b></div><span><i>○</i><em>{name==='Researcher'&&active?active.state:'Unavailable'}</em></span><p>{desc}</p></article>{i<agents.length-1&&<b className="arrow">›</b>}</div>)}</div></section>

    <div className="grid">
      <section className="card current"><div className="head"><h2>Current Activity</h2><em className="paused">○ {active?.state ?? 'Not started'}</em></div><div className="empty"><i>⌕</i><h3>{active?'Latest persisted workflow':'No workflow is running'}</h3><p>{active?`Run ${active.id.slice(0,8)} is ${active.state}. No opportunity is claimed until evidence is persisted.`:'Real agent events appear here after a permitted research source is connected.'}</p><div className="steps"><span><b>Database</b><small>{data.health?.database ?? 'Unavailable'}</small></span><span><b>Temporal</b><small>{data.health?.temporal ?? 'Unavailable'}</small></span><span><b>Research provider</b><small>{data.health?.researchProvider ?? 'Unavailable'}</small></span><span><b>Paid budget</b><small>$0</small></span></div></div></section>
      <section className="card portfolio"><div className="head"><h2>Opportunity Candidates</h2><button>View All ›</button></div>{data.opportunities.length?data.opportunities.slice(0,3).map(item=><div className="candidate" key={item.id}><span><b>{item.title}</b><small>{item.rationale}</small></span><em>{item.scorecard.total ?? '—'}/100</em><a href={item.evidence[0]?.sourceUrl} target="_blank" rel="noreferrer">Evidence ↗</a><CandidateActions approvalId={item.approvalId} opportunityId={item.id} phase2Ready={item.phase2Readiness?.ready===true}/></div>):<div className="noProject"><i>□</i><span><b>No opportunities yet</b><small>A real research run must store attributed evidence first.</small></span></div>}<Provider name="Research source" detail="Stack Exchange problem signals + Wikimedia topic interest; neither is search volume" state={data.health?.researchProvider ?? 'Unavailable'} off={data.health?.researchProvider!=='available'}/></section>
      <section className="card recent"><div className="head"><h2>Recent Activity</h2><button>View All Activity ›</button></div>{data.activity.events.length?data.activity.events.slice(0,4).map(event=><div className="event" key={event.id}><i>✓</i><span><b>{event.eventType}</b><small>{event.payload.reason ?? `Workflow ${event.aggregateId?.slice(0,8) ?? ''}`}</small></span><time>{new Date(event.occurredAt).toLocaleString('en-GB',{timeZone:'Asia/Karachi'})}</time></div>):<div className="event muted"><i>○</i><span><b>No runtime events yet</b><small>This feed never displays simulated agent activity</small></span></div>}</section>
      <section className="card performance"><div className="head"><h2>SEO &amp; Performance <span>(All Websites)</span></h2><div className="range"><b>7D</b><b className="on">30D</b><b>90D</b></div></div><div className="perf"><Metric value="—" label="Total Clicks" detail="Search Console not connected"/><Metric value="—" label="Impressions" detail="No measured data"/><Metric value="—" label="Average CTR" detail={glossary.ctr}/><Metric value="0" label="Keywords Ranking" detail="No live websites"/></div></section>
    </div>
  </main>
</div>}

function Provider({name,detail,state,off=false}:{name:string;detail:string;state:string;off?:boolean}){return <div className="provider"><span><b>{name}</b><small>{detail}</small></span><em className={off?'off':''}>{state}</em></div>}
function Metric({value,label,detail}:{value:string;label:string;detail:string}){return <div><b>{value}</b><small>{label}</small><span>{detail}</span></div>}

function MarketStudyView({study}:{study:MarketStudy}) {
  const dimensions=['demand','intent','serp_reality','competitor_quality','content_product_gap','topic_traffic_potential','click_potential','solution_fit','authority_requirement','build_feasibility','strategic_value'];
  return <div className="studyView">
    <div className="studyMeta"><span><b>Study brief</b><small>{study.brief}</small></span><span><b>Limits</b><small>{study.sourcePolicy.replaceAll('_',' ')} · {study.requestLimit} request · {study.timeLimitSeconds}s · ${study.paidBudgetCents/100}</small></span><span><b>Workflow</b><small>{study.workflowState}</small></span></div>
    <div className="readinessBanner"><b>{study.opportunities.some(item=>item.phase2Readiness.ready)?'Evidence gate passed for at least one candidate':'Build remains locked'}</b><span>{study.opportunities.some(item=>item.phase2Readiness.ready)?'An explicit owner approval would still be required.':'No candidate has enough fresh, non-conflicting direct evidence. Resolve every listed blocker before Build can be considered.'}</span></div>
    <div className="providerMatrix"><h3>Evidence capability status</h3><div>{study.providers.map(provider=>{const setup=providerSetup(provider);const state=providerState(provider);return <article key={provider.providerId}><span><b>{provider.capability.replaceAll('_',' ')}</b><small>{provider.providerId} · {provider.evidenceNature||'unknown'} evidence · {provider.geography||'geography unknown'}</small></span><em className={state.className}>{state.label}</em><p>{provider.reason}</p>{setup?<div className="setupAction"><b>{setup.action}</b><small>{setup.why}</small></div>:null}<p><b>Could resolve:</b> {provider.resolvesDimensions?.join(', ')||'No decision dimension by itself'}</p>{provider.limitations?.length?<p><b>Limits:</b> {provider.limitations.join(' ')}</p>:null}{provider.documentationUrl?<a href={provider.documentationUrl} target="_blank" rel="noreferrer">Provider documentation ↗</a>:null}</article>})}</div></div>
    {study.opportunities.length?<div className="comparison" role="region" aria-label="Opportunity comparison" tabIndex={0}>
      <table><thead><tr><th>Validation dimension</th>{study.opportunities.map(item=><th key={item.id}><b>{item.title}</b><span className={`recommendation ${item.recommendation}`}>{item.recommendation.replace('_',' ')}</span><small>{item.scorecard.total}/100 · {Math.round(item.scorecard.evidenceCoverage*100)}% evidence coverage</small></th>)}</tr></thead>
      <tbody>{dimensions.map(dimension=><tr key={dimension}><th>{dimension.replaceAll('_',' ')}<small>{termHelp(dimension)}</small></th>{study.opportunities.map(item=>{const finding=item.findings.find(entry=>entry.dimension===dimension);return <td key={item.id}><span className={`claim ${finding?.classification??'unknown'}`}>{finding?.classification??'unknown'}</span><p>{finding?.claim??'No permitted evidence captured.'}</p></td>})}</tr>)}</tbody></table>
    </div>:<div className="noStudy"><b>Research is {study.status}.</b><span>Evidence-backed candidates will appear here only after the worker persists them.</span></div>}
    {study.opportunities.map(item=><details className="candidateDetail" key={item.id}><summary><b>{item.title}</b><span>{item.phase2Readiness.ready?'Phase 2 evidence gate passed':`More research required · ${item.unknowns.length} unknowns`}</span></summary><div><p><b>Problem:</b> {item.problem}</p><p><b>Audience:</b> {item.audience}</p><p><b>Search hypothesis:</b> {item.searchDemandHypothesis}</p><p><b>Product formats:</b> {item.productFormats.join(' · ')}</p><p><b>Topic clusters:</b> {item.topicClusters.join(' · ')}</p><p><b>Representative queries:</b> {item.queryExamples.join(' · ')}</p><p><b>Content/tool gaps:</b> {[...item.contentGaps,...item.toolGaps].join(' · ')}</p><p><b>Initial IA:</b> {item.informationArchitecture.join(' → ')}</p><p><b>Why Build is blocked:</b> {item.phase2Readiness.blockers.join(' · ')}</p><p><b>Providers that could help:</b> {study.providers.filter(provider=>provider.resolvesDimensions?.some(dimension=>item.phase2Readiness.blockers.some(blocker=>blocker.startsWith(dimension)))).map(provider=>provider.providerId).join(' · ')||'No approved provider currently resolves every blocker.'}</p><p><b>Risks:</b> {item.risks.join(' · ')}</p><p className="evidenceLinks"><b>Evidence:</b> {item.evidence.map((entry,index)=><span key={entry.id}>{index>0?' · ':''}<a href={entry.sourceUrl} target="_blank" rel="noreferrer">{entry.subject||`Source ${index+1}`} ↗</a><small> {entry.evidenceNature||'unknown'} · {entry.geography||'geography unknown'} · confidence {Math.round(Number(entry.confidence)*100)}%{entry.stale?' · STALE':''}</small>{entry.measurement?.value!==null&&entry.measurement?<small> · {entry.measurement.value.toLocaleString('en-US')} {entry.measurement.unit}{entry.measurement.absoluteSearchDemand?'':' · not search volume'}</small>:null}</span>)}</p></div></details>)}
  </div>;
}

function termHelp(term:string){return ({demand:'Authorized evidence that people seek this problem; UNKNOWN is not zero.',intent:'What people are trying to accomplish.',serp_reality:'What live search results actually contain.',competitor_quality:'How well current specialists and substitutes solve the job.',content_product_gap:'A specific unmet need supported by observations.',topic_traffic_potential:'Possible subject reach; not fabricated search volume.',click_potential:'Whether a result could earn a click after SERP features.',solution_fit:'Whether the proposed format fits the user job.',authority_requirement:'The trust and expertise likely required.',build_feasibility:'Relative implementation and maintenance effort.',strategic_value:'Reusable learning, distribution and portfolio value.'} as Record<string,string>)[term]}
function providerSetup(provider:ProviderRun){if(provider.availability==='available')return null;if(provider.providerId==='brave-search-api')return{action:'Setup required: Brave Search credential plus a scoped owner-approved budget.',why:'Live ranked results are needed to understand result types, repeated competitors, intent and likely click competition.'};if(provider.capability==='search_demand'||provider.capability==='keyword_discovery')return{action:'Setup required: approve one keyword-demand provider.',why:'Direct location-targeted keyword history is required to show that people actually search for each problem.'};if(provider.capability==='authority_difficulty')return{action:'Evidence still required: approved authority source.',why:'This prevents the system from recommending a market that requires unrealistic trust or link authority.'};return null;}
function providerState(provider:ProviderRun){if(provider.providerId!=='brave-search-api')return{label:provider.availability.toUpperCase(),className:provider.availability};const reason=provider.reason.toLowerCase();if(provider.availability==='available'&&provider.requestCount>0)return{label:'AVAILABLE',className:'available'};if(reason.includes('credential'))return{label:'CREDENTIAL MISSING',className:'unavailable'};if(reason.includes('budget')||reason.includes('approval'))return{label:'BUDGET APPROVAL MISSING',className:'blocked'};return{label:'ADAPTER READY',className:'blocked'};}
