CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE workspaces (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), owner_id uuid NOT NULL, name text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE workflow_runs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id uuid NOT NULL REFERENCES workspaces(id), idempotency_key text NOT NULL, state text NOT NULL, temporal_workflow_id text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(workspace_id, idempotency_key));
CREATE TABLE evidence_items (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id uuid NOT NULL REFERENCES workspaces(id), source_url text NOT NULL, captured_at timestamptz NOT NULL, reference text NOT NULL, language text NOT NULL, market text NOT NULL, confidence numeric NOT NULL CHECK(confidence BETWEEN 0 AND 1), retention text NOT NULL, integrity_hash text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE opportunities (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id uuid NOT NULL REFERENCES workspaces(id), workflow_run_id uuid REFERENCES workflow_runs(id), title text NOT NULL, lifecycle text NOT NULL, limitations jsonb NOT NULL DEFAULT '[]', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE approval_requests (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id uuid NOT NULL REFERENCES workspaces(id), workflow_run_id uuid REFERENCES workflow_runs(id), action text NOT NULL, input_snapshot jsonb NOT NULL, state text NOT NULL, expires_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE projects (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id uuid NOT NULL REFERENCES workspaces(id), opportunity_id uuid NOT NULL REFERENCES opportunities(id), state text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(opportunity_id));
CREATE TABLE outbox_events (id uuid PRIMARY KEY, aggregate_type text NOT NULL, aggregate_id uuid NOT NULL, event_type text NOT NULL, event_version integer NOT NULL, payload jsonb NOT NULL, occurred_at timestamptz NOT NULL, published_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX outbox_events_unpublished_idx ON outbox_events(created_at) WHERE published_at IS NULL;
