import { createHash } from 'node:crypto';
import type { ProviderResult } from '@venture/contracts';

type FetchLike = typeof fetch;
type BraveResult = { title?:string; url?:string; description?:string; type?:string; extra_snippets?:string[] };
type BraveResponse = { query?:{more_results_available?:boolean}; web?:{results?:BraveResult[]}; news?:{results?:unknown[]}; videos?:{results?:unknown[]}; discussions?:{results?:unknown[]}; locations?:{results?:unknown[]}; faq?:{results?:unknown[]}; infobox?:unknown; rich?:unknown };
export type SerpFeature='web'|'news'|'videos'|'discussions'|'locations'|'faq'|'infobox'|'rich';
export type SearchIntent='informational'|'commercial_investigation'|'transactional'|'local'|'navigational'|'mixed'|'unknown';
export type SiteSpecialization='specialist'|'broad'|'unknown';
export type SerpObservation={providerId:string;query:string;country:string;language:string;capturedAt:string;position:number;domain:string;url:string;title:string;snippet:string;extraSnippets:string[];pageType:string;contentType:string;contentDepth:'unknown';siteSpecialization:SiteSpecialization;specializationReason:string;specializationConfidence:number;visibleAuthoritySignals:string[];technicalQuality:'unknown';intentMatch:{kind:'proxy';confidence:number;reason:string};observedIntent:SearchIntent;businessModel:'unknown';strengths:string[];weaknesses:string[];beatable:'unknown';repeatedDomainCount:number;serpFeatures:SerpFeature[];limitations:string[]};
export type BraveRawProvenance={endpoint:string;query:string;country:string;language:string;requestedAt:string;receivedAt:string;responseSha256:string;responseBody:unknown;responseHeaders:Record<string,string>;providerRequestId?:string|undefined};
export type BraveSerpBatch={observations:SerpObservation[];summary:{query:string;country:string;language:string;serpFeatures:SerpFeature[];repeatedDomains:Array<{domain:string;count:number}>;observedIntent:SearchIntent;moreResultsAvailable:boolean};provenance:BraveRawProvenance};
export type BraveBudgetApproval={approvalId:string;approvedBudgetCents:number;maxRequests:number};
export type BraveAttempt={outcome:'available'|'partial'|'blocked'|'unavailable'|'failed'|'rate_limited';requestCount:number;estimatedCostMicrousd:number;httpStatus?:number|undefined;retryAfterSeconds?:number|undefined;providerRequestId?:string|undefined};
export type BraveProviderResult=ProviderResult<BraveSerpBatch[]>&{attempt:BraveAttempt};
const COST_MICROUSD_PER_REQUEST=5_000;

export class BraveSearchSource{
  readonly name='brave-search-api';
  constructor(private readonly token:string|undefined,private readonly fetcher:FetchLike=fetch,private readonly now:()=>Date=()=>new Date()){}
  async searchMany(input:{queries:Array<{query:string;country:string;language:string;count?:number}>;budgetApproval?:BraveBudgetApproval}):Promise<BraveProviderResult>{
    if(!this.token)return unavailable('Brave Search credential is not configured.');
    if(!input.budgetApproval?.approvalId||input.budgetApproval.approvedBudgetCents<=0||input.budgetApproval.maxRequests<=0)return blocked('Brave Search requires an explicit budget approval ID, positive approved budget and request limit.');
    const unique=[...new Map(input.queries.map(item=>[`${item.query}\u0000${item.country}\u0000${item.language}`,item])).values()];
    if(!unique.length)return unavailable('No live SERP query was supplied.');
    if(unique.length>input.budgetApproval.maxRequests)return blocked(`Requested ${unique.length} queries but approval permits ${input.budgetApproval.maxRequests}.`);
    if(unique.length*COST_MICROUSD_PER_REQUEST>input.budgetApproval.approvedBudgetCents*10_000)return blocked(`Projected Brave cost exceeds approved budget for ${unique.length} queries.`);
    const batches:BraveSerpBatch[]=[];let estimatedCostMicrousd=0;
    for(const query of unique){const result=await this.searchOne(query);estimatedCostMicrousd+=result.attempt.estimatedCostMicrousd;if(result.availability!=='available'||!result.value){if(!batches.length)return result;return{...result,availability:'available',value:batches,reason:`Partial result: ${result.reason??'later query failed.'}`,attempt:{...result.attempt,outcome:'partial',requestCount:batches.length+result.attempt.requestCount,estimatedCostMicrousd}};}batches.push(...result.value);}
    const partial=batches.some(batch=>batch.observations.length<(unique.find(item=>item.query===batch.summary.query)?.count??10));
    return partial?{availability:'available',value:batches,reason:'Partial result: one or more queries returned fewer usable web results than requested.',attempt:{outcome:'partial',requestCount:batches.length,estimatedCostMicrousd}}:{availability:'available',value:batches,attempt:{outcome:'available',requestCount:batches.length,estimatedCostMicrousd}};
  }
  async search(input:{query:string;country:string;language:string;count?:number;budgetApproval?:BraveBudgetApproval}){return input.budgetApproval?this.searchMany({queries:[input],budgetApproval:input.budgetApproval}):this.searchMany({queries:[input]});}
  private async searchOne(input:{query:string;country:string;language:string;count?:number}):Promise<BraveProviderResult>{
    const count=Math.min(20,Math.max(1,input.count??10));const url=new URL('https://api.search.brave.com/res/v1/web/search');url.search=new URLSearchParams({q:input.query,country:input.country,search_lang:input.language,count:String(count),safesearch:'moderate',extra_snippets:'true'}).toString();const requestedAt=this.now().toISOString();
    try{const response=await this.fetcher(url,{headers:{accept:'application/json','x-subscription-token':this.token!},signal:AbortSignal.timeout(15_000)});const receivedAt=this.now().toISOString();const rawText=await response.text();const rawBody=parseJson(rawText);const providerRequestId=response.headers.get('x-request-id')??response.headers.get('x-trace-id')??undefined;const base={requestCount:1,estimatedCostMicrousd:COST_MICROUSD_PER_REQUEST,httpStatus:response.status,providerRequestId};
      if(response.status===429)return{availability:'unavailable',reason:'Brave Search rate limit reached; retry after the recorded delay.',attempt:{...base,outcome:'rate_limited',retryAfterSeconds:retryAfterSeconds(response.headers.get('retry-after'),this.now())}};
      if(!response.ok)return{availability:'unavailable',reason:`Brave Search API returned HTTP ${response.status}.`,attempt:{...base,outcome:response.status>=500?'failed':'unavailable'}};
      const body=rawBody as BraveResponse;const results=body.web?.results??[];const serpFeatures=detectFeatures(body);const observedIntent=inferSearchIntent(input.query,serpFeatures,results);const domainCounts=new Map<string,number>();for(const item of results)try{const domain=new URL(item.url??'').hostname;domainCounts.set(domain,(domainCounts.get(domain)??0)+1);}catch{}
      const observations=results.flatMap((item,index)=>{if(!item.url||!item.title)return[];let parsed:URL;try{parsed=new URL(item.url);}catch{return[];}const queryTerms=input.query.toLowerCase().split(/\s+/).filter(term=>term.length>2);const haystack=`${item.title} ${item.description??''}`.toLowerCase();const matched=queryTerms.filter(term=>haystack.includes(term)).length;const specialization=inferSpecialization(parsed,item.title,item.description??'',input.query);return[{providerId:this.name,query:input.query,country:input.country,language:input.language,capturedAt:receivedAt,position:index+1,domain:parsed.hostname,url:item.url,title:item.title,snippet:item.description??'',extraSnippets:item.extra_snippets??[],pageType:inferPageType(parsed.pathname,item.title),contentType:item.type??'web',contentDepth:'unknown' as const,siteSpecialization:specialization.value,specializationReason:specialization.reason,specializationConfidence:specialization.confidence,visibleAuthoritySignals:[],technicalQuality:'unknown' as const,intentMatch:{kind:'proxy' as const,confidence:queryTerms.length?Number((matched/queryTerms.length).toFixed(2)):0,reason:'Lexical overlap in result title/snippet; page review is still required.'},observedIntent,businessModel:'unknown' as const,strengths:['Ranks in the captured Brave result set.'],weaknesses:['Content depth, technical quality and authority are not established from a snippet.'],beatable:'unknown' as const,repeatedDomainCount:domainCounts.get(parsed.hostname)??1,serpFeatures,limitations:['Position is from Brave Search for the captured country/language/time, not Google.','Snippet-level observation cannot establish page quality, backlinks, traffic, DR, DA or organic difficulty.']}];});
      if(!observations.length)return{availability:'unavailable',reason:'Brave Search returned no usable web results.',attempt:{...base,outcome:'unavailable'}};
      const responseHeaders=pickHeaders(response.headers,['content-type','x-request-id','x-trace-id','x-ratelimit-limit','x-ratelimit-remaining','x-ratelimit-reset']);const batch:BraveSerpBatch={observations,summary:{query:input.query,country:input.country,language:input.language,serpFeatures,repeatedDomains:[...domainCounts].filter(([,value])=>value>1).map(([domain,value])=>({domain,count:value})),observedIntent,moreResultsAvailable:body.query?.more_results_available===true},provenance:{endpoint:url.toString(),query:input.query,country:input.country,language:input.language,requestedAt,receivedAt,responseSha256:createHash('sha256').update(rawText).digest('hex'),responseBody:rawBody,responseHeaders,providerRequestId}};const partial=observations.length<count;return partial?{availability:'available',value:[batch],reason:`Partial result: requested ${count}, received ${observations.length} usable web results.`,attempt:{...base,outcome:'partial'}}:{availability:'available',value:[batch],attempt:{...base,outcome:'available'}};
    }catch(error){return{availability:'unavailable',reason:`Brave Search request failed: ${error instanceof Error?error.message:'Unknown network failure'}`,attempt:{outcome:'failed',requestCount:1,estimatedCostMicrousd:COST_MICROUSD_PER_REQUEST}};}
  }
}
function unavailable(reason:string):BraveProviderResult{return{availability:'unavailable',reason,attempt:{outcome:'unavailable',requestCount:0,estimatedCostMicrousd:0}};}function blocked(reason:string):BraveProviderResult{return{availability:'blocked',reason,attempt:{outcome:'blocked',requestCount:0,estimatedCostMicrousd:0}};}
function parseJson(text:string):unknown{try{return JSON.parse(text);}catch{return{text:text.slice(0,4_000)}};}function pickHeaders(headers:Headers,names:string[]){return Object.fromEntries(names.flatMap(name=>{const value=headers.get(name);return value?[[name,value]]:[]}));}function retryAfterSeconds(value:string|null,now:Date){if(!value)return undefined;const seconds=Number(value);if(Number.isFinite(seconds))return Math.max(0,Math.ceil(seconds));const date=Date.parse(value);return Number.isFinite(date)?Math.max(0,Math.ceil((date-now.getTime())/1000)):undefined;}
function detectFeatures(body:BraveResponse):SerpFeature[]{return(['web','news','videos','discussions','locations','faq','infobox','rich'] as SerpFeature[]).filter(key=>{const value=body[key as keyof BraveResponse] as {results?:unknown[]}|undefined;return Array.isArray(value?.results)?value.results.length>0:Boolean(value);});}
function inferSearchIntent(query:string,features:SerpFeature[],results:BraveResult[]):SearchIntent{const text=query.toLowerCase();const types=results.flatMap(item=>{try{return[inferPageType(new URL(item.url??'').pathname,item.title??'')];}catch{return[];}});const intents=new Set<SearchIntent>();if(/near me|in pakistan|karachi|lahore|islamabad/.test(text)||features.includes('locations'))intents.add('local');if(/buy|price|pricing|hire|service|agency/.test(text))intents.add('transactional');if(/best|compare|versus|vs|review|tool|software/.test(text)||types.includes('comparison'))intents.add('commercial_investigation');if(/how|what|why|guide|learn|tutorial|check|audit|troubleshoot/.test(text)||types.includes('guide'))intents.add('informational');return intents.size>1?'mixed':intents.values().next().value??'unknown';}
function inferSpecialization(url:URL,title:string,snippet:string,query:string):{value:SiteSpecialization;reason:string;confidence:number}{const domain=url.hostname.replace(/^www\./,'');const label=domain.split('.')[0]??'';const queryTerms=query.toLowerCase().split(/\W+/).filter(term=>term.length>3);const text=`${domain} ${title} ${snippet}`.toLowerCase();const matches=queryTerms.filter(term=>text.includes(term)).length;if(matches>=2||/(seo|searchengine|marketing|webmaster|keyword)/.test(label))return{value:'specialist',reason:'Domain or result text is strongly focused on the observed search topic.',confidence:0.65};if(['wikipedia.org','youtube.com','reddit.com','github.com','linkedin.com','medium.com'].some(value=>domain===value||domain.endsWith(`.${value}`)))return{value:'broad',reason:'Domain serves many topics rather than specializing in this search problem.',confidence:0.8};return{value:'unknown',reason:'Snippet and domain alone do not establish whether the site is a specialist.',confidence:0.3};}
function inferPageType(path:string,title:string){const text=`${path} ${title}`.toLowerCase();if(/compare|comparison|versus|\bvs\b|best-/.test(text))return'comparison';if(/tool|checker|audit|calculator/.test(text))return'tool';if(/guide|learn|how|what|why|tutorial/.test(text))return'guide';if(/category|directory|list/.test(text))return'directory';if(/product|pricing|plans/.test(text))return'commercial_page';return'page_unknown';}
